/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import audio.AePlayWave;
import audio.PlayAudio;
import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Alondra
 */
public class JuegoGatito extends javax.swing.JFrame {

    /**
     * Creates new form JuegoGatito
     */
    public JuegoGatito() {
        initComponents();
    }
///
    private boolean isXorO = false; //FALSE = O || TRUE = X
    private boolean gameWon = false;
    private int turns = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnplayer1 = new javax.swing.JLabel();
        txtjugador1 = new javax.swing.JTextField();
        btnplayer2 = new javax.swing.JLabel();
        txtjugador2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btncel1 = new javax.swing.JButton();
        btncel2 = new javax.swing.JButton();
        btncel3 = new javax.swing.JButton();
        btncel4 = new javax.swing.JButton();
        btncel5 = new javax.swing.JButton();
        btncel6 = new javax.swing.JButton();
        btncel7 = new javax.swing.JButton();
        btncel8 = new javax.swing.JButton();
        btncel9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnsart = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 550));
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("MS PMincho", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gatito.jpg"))); // NOI18N
        jLabel1.setText("Juego del Gato");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(72, 10));
        jPanel2.add(jLabel1);

        jPanel6.setLayout(new java.awt.GridLayout(3, 3));

        btnplayer1.setBackground(new java.awt.Color(0, 153, 153));
        btnplayer1.setFont(new java.awt.Font("Sitka Heading", 2, 36)); // NOI18N
        btnplayer1.setForeground(new java.awt.Color(204, 204, 255));
        btnplayer1.setText("Jugador 1");
        btnplayer1.setOpaque(true);
        jPanel6.add(btnplayer1);
        jPanel6.add(txtjugador1);

        btnplayer2.setBackground(new java.awt.Color(0, 153, 153));
        btnplayer2.setFont(new java.awt.Font("Sitka Heading", 2, 36)); // NOI18N
        btnplayer2.setForeground(new java.awt.Color(204, 204, 255));
        btnplayer2.setText("Jugador 2");
        btnplayer2.setOpaque(true);
        jPanel6.add(btnplayer2);

        txtjugador2.setToolTipText("");
        jPanel6.add(txtjugador2);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Turno");
        jLabel4.setOpaque(true);
        jPanel6.add(jLabel4);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel7.setLayout(new java.awt.GridLayout(3, 3));

        btncel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_card.png"))); // NOI18N
        btncel1.setEnabled(false);
        btncel1.setPreferredSize(new java.awt.Dimension(100, 160));
        btncel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncel1ActionPerformed(evt);
            }
        });
        jPanel7.add(btncel1);

        btncel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_card.png"))); // NOI18N
        btncel2.setEnabled(false);
        btncel2.setPreferredSize(new java.awt.Dimension(100, 160));
        btncel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncel2ActionPerformed(evt);
            }
        });
        jPanel7.add(btncel2);

        btncel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_card.png"))); // NOI18N
        btncel3.setEnabled(false);
        btncel3.setPreferredSize(new java.awt.Dimension(100, 160));
        btncel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncel3ActionPerformed(evt);
            }
        });
        jPanel7.add(btncel3);

        btncel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_card.png"))); // NOI18N
        btncel4.setEnabled(false);
        btncel4.setPreferredSize(new java.awt.Dimension(100, 160));
        btncel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncel4ActionPerformed(evt);
            }
        });
        jPanel7.add(btncel4);

        btncel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_card.png"))); // NOI18N
        btncel5.setEnabled(false);
        btncel5.setPreferredSize(new java.awt.Dimension(100, 160));
        btncel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncel5ActionPerformed(evt);
            }
        });
        jPanel7.add(btncel5);

        btncel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_card.png"))); // NOI18N
        btncel6.setEnabled(false);
        btncel6.setPreferredSize(new java.awt.Dimension(100, 160));
        btncel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncel6ActionPerformed(evt);
            }
        });
        jPanel7.add(btncel6);

        btncel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_card.png"))); // NOI18N
        btncel7.setEnabled(false);
        btncel7.setPreferredSize(new java.awt.Dimension(100, 160));
        btncel7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncel7ActionPerformed(evt);
            }
        });
        jPanel7.add(btncel7);

        btncel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_card.png"))); // NOI18N
        btncel8.setEnabled(false);
        btncel8.setPreferredSize(new java.awt.Dimension(100, 160));
        btncel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncel8ActionPerformed(evt);
            }
        });
        jPanel7.add(btncel8);

        btncel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_card.png"))); // NOI18N
        btncel9.setEnabled(false);
        btncel9.setPreferredSize(new java.awt.Dimension(100, 160));
        btncel9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncel9ActionPerformed(evt);
            }
        });
        jPanel7.add(btncel9);

        jPanel5.add(jPanel7);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        btnsart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_start.png"))); // NOI18N
        btnsart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsartActionPerformed(evt);
            }
        });
        jPanel4.add(btnsart);

        jPanel5.add(jPanel4);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncel1ActionPerformed
            
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        checkButtonXO(btncel1);
        pintar();
        //whoWonGame();
// TODO add your handling code here:
    }//GEN-LAST:event_btncel1ActionPerformed

    private void btncel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncel2ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        checkButtonXO(btncel2);
        pintar();
        //whoWonGame();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncel2ActionPerformed

    private void btncel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncel3ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        checkButtonXO(btncel3);
        pintar();
        //whoWonGame();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncel3ActionPerformed

    private void btncel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncel4ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        checkButtonXO(btncel4);
        pintar();
        //whoWonGame();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncel4ActionPerformed

    private void btncel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncel5ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        checkButtonXO(btncel5);
        pintar();
        //whoWonGame();
// TODO add your handling code here:
    }//GEN-LAST:event_btncel5ActionPerformed

    private void btncel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncel6ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        checkButtonXO(btncel6);
        pintar();
        //whoWonGame();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncel6ActionPerformed

    private void btncel7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncel7ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        checkButtonXO(btncel7);
        pintar();
        //whoWonGame();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncel7ActionPerformed

    private void btncel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncel8ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        checkButtonXO(btncel8);
        pintar();
        //whoWonGame();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncel8ActionPerformed

    private void btncel9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncel9ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        checkButtonXO(btncel9);
        pintar();
        // whoWonGame();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncel9ActionPerformed

    private void btnsartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsartActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/end1.wav");//cambiar nombre y descargar audio del gato
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        checkGameStart();
        inicializar();
        

// TODO add your handling code here:
    }//GEN-LAST:event_btnsartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoGatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoGatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoGatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoGatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoGatito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncel1;
    private javax.swing.JButton btncel2;
    private javax.swing.JButton btncel3;
    private javax.swing.JButton btncel4;
    private javax.swing.JButton btncel5;
    private javax.swing.JButton btncel6;
    private javax.swing.JButton btncel7;
    private javax.swing.JButton btncel8;
    private javax.swing.JButton btncel9;
    private javax.swing.JLabel btnplayer1;
    private javax.swing.JLabel btnplayer2;
    private javax.swing.JButton btnsart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtjugador1;
    private javax.swing.JTextField txtjugador2;
    // End of variables declaration//GEN-END:variables

    public void checkButtonXO(JButton btn) {//Metodo donde se establece cuando se cambian las imagenes, dependiendo del jugador
        //!btncel2.getActionCommand().equalsIgnoreCase("x")||!btncel2.getActionCommand().equalsIgnoreCase("o")

        if (btn.getActionCommand().isEmpty()) {
            if (!isXorO) {
                //btncel2.setEnabled(false);
                btn.setActionCommand("O");
                btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_o.png")));
                isXorO = true;
            } else {
                // btncel2.setEnabled(false);
                btn.setActionCommand("X");
                btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_x.png")));
                isXorO = false;
            }
        } else {
            //turns--;
            JOptionPane.showMessageDialog(null, "Casilla ocupada");
        }

        if (turns == 9) {
            JOptionPane.showMessageDialog(null, "Game Over, nadie gano");
        } else {
            whoWonGame();
        }

    }

    public void checkGameStart() {//Es la ejecución cuando se da clic en el boton de star, se inicia el juego
        if (!txtjugador1.getText().isEmpty() && !txtjugador2.getText().isEmpty()) {

            btncel1.setEnabled(true);
            btncel2.setEnabled(true);
            btncel3.setEnabled(true);
            btncel4.setEnabled(true);
            btncel5.setEnabled(true);
            btncel6.setEnabled(true);
            btncel7.setEnabled(true);
            btncel8.setEnabled(true);
            btncel9.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese jugadores");
        }

    }

    public void whoWonGame() {//Aqui se establecen las condiciones donde se especifica quien gana
        turns++;
        if (turns == 9) {
            gameWon = true;
            //JOptionPane.showMessageDialog(null,"Game ended, no one won");
        }
        if (!btncel1.getActionCommand().isEmpty() && btncel1.getActionCommand().equals(btncel4.getActionCommand()) && btncel1.getActionCommand().equals(btncel7.getActionCommand())) {
            if (btncel1.getActionCommand().equals("X")) {
                btncel1.setIcon(new ImageIcon(getClass().getResource("/images/img_xV.png")));
                btncel4.setIcon(new ImageIcon(getClass().getResource("/images/img_xV.png")));
                btncel7.setIcon(new ImageIcon(getClass().getResource("/images/img_xV.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador1.getText());
                bloquear();
            } else {
                btncel1.setIcon(new ImageIcon(getClass().getResource("/images/img_oV.png")));
                btncel4.setIcon(new ImageIcon(getClass().getResource("/images/img_oV.png")));
                btncel7.setIcon(new ImageIcon(getClass().getResource("/images/img_oV.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador2.getText());
                bloquear();
            }
        }

        if (!btncel1.getActionCommand().isEmpty() && btncel1.getActionCommand().equals(btncel5.getActionCommand()) && btncel1.getActionCommand().equals(btncel9.getActionCommand())) {

            if (btncel1.getActionCommand().equals("X")) {
                btncel1.setIcon(new ImageIcon(getClass().getResource("/images/img_xD1.png")));
                btncel5.setIcon(new ImageIcon(getClass().getResource("/images/img_xD1.png")));
                btncel9.setIcon(new ImageIcon(getClass().getResource("/images/img_xD1.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador1.getText());
                bloquear();
            } else {
                btncel1.setIcon(new ImageIcon(getClass().getResource("/images/img_oD1.png")));
                btncel5.setIcon(new ImageIcon(getClass().getResource("/images/img_oD1.png")));
                btncel9.setIcon(new ImageIcon(getClass().getResource("/images/img_oD1.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador2.getText());
                bloquear();
            }
        }

        if (!btncel1.getActionCommand().isEmpty() && btncel1.getActionCommand().equals(btncel2.getActionCommand()) && btncel1.getActionCommand().equals(btncel3.getActionCommand())) {

            if (btncel1.getActionCommand().equals("X")) {
                btncel1.setIcon(new ImageIcon(getClass().getResource("/images/img_xH.png")));
                btncel2.setIcon(new ImageIcon(getClass().getResource("/images/img_xH.png")));
                btncel3.setIcon(new ImageIcon(getClass().getResource("/images/img_xH.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador1.getText());
                bloquear();
            } else {
                btncel1.setIcon(new ImageIcon(getClass().getResource("/images/img_oH.png")));
                btncel2.setIcon(new ImageIcon(getClass().getResource("/images/img_oH.png")));
                btncel3.setIcon(new ImageIcon(getClass().getResource("/images/img_oH.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador2.getText());
                bloquear();
            }
        }

        if (!btncel9.getActionCommand().isEmpty() && btncel9.getActionCommand().equals(btncel6.getActionCommand()) && btncel9.getActionCommand().equals(btncel3.getActionCommand())) {

            if (btncel9.getActionCommand().equals("X")) {
                btncel9.setIcon(new ImageIcon(getClass().getResource("/images/img_xV.png")));
                btncel6.setIcon(new ImageIcon(getClass().getResource("/images/img_xV.png")));
                btncel3.setIcon(new ImageIcon(getClass().getResource("/images/img_xV.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador1.getText());
                bloquear();
            } else {
                btncel9.setIcon(new ImageIcon(getClass().getResource("/images/img_oV.png")));
                btncel6.setIcon(new ImageIcon(getClass().getResource("/images/img_oV.png")));
                btncel3.setIcon(new ImageIcon(getClass().getResource("/images/img_oV.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador2.getText());
                bloquear();
            }
        }

        if (!btncel9.getActionCommand().isEmpty() && btncel9.getActionCommand().equals(btncel8.getActionCommand()) && btncel9.getActionCommand().equals(btncel7.getActionCommand())) {

            if (btncel9.getActionCommand().equals("X")) {
                btncel9.setIcon(new ImageIcon(getClass().getResource("/images/img_xH.png")));
                btncel8.setIcon(new ImageIcon(getClass().getResource("/images/img_xH.png")));
                btncel7.setIcon(new ImageIcon(getClass().getResource("/images/img_xH.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador1.getText());
                bloquear();
            } else {
                btncel9.setIcon(new ImageIcon(getClass().getResource("/images/img_oH.png")));
                btncel8.setIcon(new ImageIcon(getClass().getResource("/images/img_oH.png")));
                btncel7.setIcon(new ImageIcon(getClass().getResource("/images/img_oH.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador2.getText());
                bloquear();
            }
        }
        if (!btncel7.getActionCommand().isEmpty() && btncel7.getActionCommand().equals(btncel5.getActionCommand()) && btncel7.getActionCommand().equals(btncel3.getActionCommand())) {

            if (btncel7.getActionCommand().equals("X")) {
                btncel7.setIcon(new ImageIcon(getClass().getResource("/images/img_xD2.png")));
                btncel5.setIcon(new ImageIcon(getClass().getResource("/images/img_xD2.png")));
                btncel3.setIcon(new ImageIcon(getClass().getResource("/images/img_xD2.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador1.getText());
                bloquear();
            } else {
                btncel7.setIcon(new ImageIcon(getClass().getResource("/images/img_oD2.png")));
                btncel5.setIcon(new ImageIcon(getClass().getResource("/images/img_oD2.png")));
                btncel3.setIcon(new ImageIcon(getClass().getResource("/images/img_oD2.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador2.getText());
                bloquear();
            }
        }

        if (!btncel6.getActionCommand().isEmpty() && btncel6.getActionCommand().equals(btncel5.getActionCommand()) && btncel6.getActionCommand().equals(btncel4.getActionCommand())) {

            if (btncel6.getActionCommand().equals("X")) {
                btncel6.setIcon(new ImageIcon(getClass().getResource("/images/img_xH.png")));
                btncel5.setIcon(new ImageIcon(getClass().getResource("/images/img_xH.png")));
                btncel4.setIcon(new ImageIcon(getClass().getResource("/images/img_xH.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador1.getText());
                bloquear();
            } else {
                btncel6.setIcon(new ImageIcon(getClass().getResource("/images/img_oH.png")));
                btncel5.setIcon(new ImageIcon(getClass().getResource("/images/img_oH.png")));
                btncel4.setIcon(new ImageIcon(getClass().getResource("/images/img_oH.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador2.getText());
                bloquear();
            }
        }
        if (!btncel2.getActionCommand().isEmpty() && btncel2.getActionCommand().equals(btncel5.getActionCommand()) && btncel2.getActionCommand().equals(btncel8.getActionCommand())) {

            if (btncel2.getActionCommand().equals("X")) {
                btncel2.setIcon(new ImageIcon(getClass().getResource("/images/img_xV.png")));
                btncel5.setIcon(new ImageIcon(getClass().getResource("/images/img_xV.png")));
                btncel8.setIcon(new ImageIcon(getClass().getResource("/images/img_xV.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador1.getText());
                bloquear();
            } else {
                btncel2.setIcon(new ImageIcon(getClass().getResource("/images/img_oV.png")));
                btncel5.setIcon(new ImageIcon(getClass().getResource("/images/img_oV.png")));
                btncel8.setIcon(new ImageIcon(getClass().getResource("/images/img_oV.png")));
                JOptionPane.showMessageDialog(null, "Ganaste " + txtjugador2.getText());
                bloquear();
            }
        }

    }

    public void inicializar() {//Se reinicia el juego cuando ya se termino
        btncel1.setIcon(new ImageIcon((getClass().getResource("/images/img_card.png"))));
        btncel2.setIcon(new ImageIcon((getClass().getResource("/images/img_card.png"))));
        btncel3.setIcon(new ImageIcon((getClass().getResource("/images/img_card.png"))));
        btncel4.setIcon(new ImageIcon((getClass().getResource("/images/img_card.png"))));
        btncel5.setIcon(new ImageIcon((getClass().getResource("/images/img_card.png"))));
        btncel6.setIcon(new ImageIcon((getClass().getResource("/images/img_card.png"))));
        btncel7.setIcon(new ImageIcon((getClass().getResource("/images/img_card.png"))));
        btncel8.setIcon(new ImageIcon((getClass().getResource("/images/img_card.png"))));
        btncel9.setIcon(new ImageIcon((getClass().getResource("/images/img_card.png"))));

        btncel1.setActionCommand(null);
        btncel2.setActionCommand(null);
        btncel3.setActionCommand(null);
        btncel4.setActionCommand(null);
        btncel5.setActionCommand(null);
        btncel6.setActionCommand(null);
        btncel7.setActionCommand(null);
        btncel8.setActionCommand(null);
        btncel9.setActionCommand(null);

        turns = 1;
        
        btnplayer1.setBackground(new java.awt.Color(0, 153, 153));
        btnplayer2.setBackground(new java.awt.Color(0, 153, 153));

//        txtjugador1.setText("");
//        txtjugador2.setText("");
    }

    
    public void bloquear(){//En esta parte se bloquea para evitat que se siga jugando cuando el juego ya termino
        btncel1.setEnabled(false);
        btncel2.setEnabled(false);
        btncel3.setEnabled(false);
        btncel4.setEnabled(false);
        btncel5.setEnabled(false);
        btncel6.setEnabled(false);
        btncel7.setEnabled(false);
        btncel8.setEnabled(false);
        btncel9.setEnabled(false);
    }
    
    public void pintar(){
        if(isXorO){
            btnplayer1.setBackground(Color.CYAN);
            btnplayer2.setBackground(Color.GRAY);
        }else{
            btnplayer1.setBackground(Color.GRAY);
            btnplayer2.setBackground(Color.CYAN);
        }
        
    }
    
    
    public void gameWon() {

        if (gameWon && turns == 9) {
            JOptionPane.showMessageDialog(null, "Game over, nadie gano");
        }

        if (gameWon) {
            if (!isXorO) {
                gameWon = true;
                JOptionPane.showMessageDialog(null, txtjugador1.getText() + " ha ganado el juego");
            } else {
                gameWon = true;
                JOptionPane.showMessageDialog(null, txtjugador2.getText() + " ha ganado el juego");
            }

        }
    }

}
